services:
  ollama:
    build: ./ollama
    container_name: bff-ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  mcp:
    build: ./simple-mcp
    container_name: storyteller-mcp
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  ollama_data:
